# -*- coding: utf-8 -*-
"""Base do projeto de Processamento de Imagens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snDMHk7RrDKDga14Zajc7Qe6hMJkQG5q
"""

import cv2 as cv
from google.colab import files
from PIL import Image
import io
import numpy as np
import matplotlib.pylab as plt
from google.colab.patches import cv2_imshow

"""Primeira parte - função de upload de imagens"""

def upload_imagem():
  uploaded = files.upload()

  if not uploaded:
    print("Nenhuma imagem foi selecionada para Upload")
    return None

  for nome_arquivo in uploaded.keys():
    print(f"Imagem {nome_arquivo} enviada com sucesso.")
    return nome_arquivo

upload_imagem()

def separador():
  print("--------------------------------------------- \n")

def separar_canais(caminho):
  imagem = caminho
  imagem = cv.imread(imagem)

  img_rgb = cv.cvtColor(imagem,cv.COLOR_BGR2RGB)
  img_hsv = cv.cvtColor(imagem,cv.COLOR_BGR2HSV)
  img_lab = cv.cvtColor(imagem,cv.COLOR_BGR2LAB)

  print("Imagem em RGB")
  cv2_imshow(img_rgb)

  separador()

  print("Imagem em HSV")
  cv2_imshow(img_hsv)

  separador()

  print("Imagem em LAB")
  cv2_imshow(img_lab)

imagem1 = cv.imread('/content/20250921_192145.jpg')
cv2_imshow(imagem1)

separar_canais("/content/20250921_192145.jpg")